import React from 'react';
import { Link } from 'react-router-dom';
import { Sprout, ShieldAlert, PhoneCall, Heart, ExternalLink } from 'lucide-react';

export const Footer: React.FC = () => {
  return (
    <footer className="bg-slate-900 text-slate-300 pt-12 pb-8 border-t border-slate-800 mt-auto">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Safety Disclaimer Banner */}
        <div className="bg-amber-950/40 border border-amber-600/30 rounded-2xl p-5 mb-10 text-amber-200/90 text-xs sm:text-sm leading-relaxed flex items-start gap-3">
          <ShieldAlert className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
          <div>
            <span className="font-bold text-amber-300 block mb-1">
              Official Agricultural Advisory Notice & Safety Disclaimer
            </span>
            <p className="text-amber-100/80">
              The recommendations generated by AgroAI are advisory decisions based on structured farm inputs and Google's Gemini AI. 
              They are intended to assist informed decision-making and do not substitute for in-person evaluations by certified local agricultural extension officers, certified agronomists, or official government agricultural advisories. Always verify chemical application guidelines with local regulatory authorities and follow standard safety protocols when applying farm inputs.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 pb-10 border-b border-slate-800">
          {/* Brand Info */}
          <div className="md:col-span-1 space-y-3">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-emerald-600 flex items-center justify-center text-white">
                <Sprout className="w-5 h-5" />
              </div>
              <span className="text-lg font-bold text-white tracking-tight">AgroAI Assistant</span>
            </div>
            <p className="text-xs text-slate-400 leading-relaxed">
              Empowering farmers with precision crop advisories, soil health insights, water management schedules, and IPM pest guidance powered by Google Gemini.
            </p>
          </div>

          {/* Core Modules */}
          <div>
            <h4 className="text-xs font-semibold text-white uppercase tracking-wider mb-3">
              Advisory Domains
            </h4>
            <ul className="space-y-2 text-xs text-slate-400">
              <li><Link to="/advisory?category=crop_selection" className="hover:text-emerald-400 transition-colors">Crop Selection & Suitability</Link></li>
              <li><Link to="/advisory?category=crop_management" className="hover:text-emerald-400 transition-colors">Growth Stage Care & Weeding</Link></li>
              <li><Link to="/advisory?category=irrigation" className="hover:text-emerald-400 transition-colors">Precision Irrigation Schedules</Link></li>
              <li><Link to="/advisory?category=fertilizer" className="hover:text-emerald-400 transition-colors">Balanced NPK & Soil Nutrition</Link></li>
              <li><Link to="/advisory?category=pest_disease" className="hover:text-emerald-400 transition-colors">Integrated Pest & Disease IPM</Link></li>
            </ul>
          </div>

          {/* Farmer Resources */}
          <div>
            <h4 className="text-xs font-semibold text-white uppercase tracking-wider mb-3">
              Farmer Resources
            </h4>
            <ul className="space-y-2 text-xs text-slate-400">
              <li><Link to="/advisory/new" className="hover:text-emerald-400 transition-colors">Request New Advisory</Link></li>
              <li><Link to="/history" className="hover:text-emerald-400 transition-colors">Past Advisories Archive</Link></li>
              <li><Link to="/farm" className="hover:text-emerald-400 transition-colors">Farm Soil & Water Profiles</Link></li>
              <li><Link to="/settings" className="hover:text-emerald-400 transition-colors">Language Preferences</Link></li>
            </ul>
          </div>

          {/* Emergency & Support */}
          <div>
            <h4 className="text-xs font-semibold text-white uppercase tracking-wider mb-3">
              Support & Extension
            </h4>
            <div className="bg-slate-800/80 rounded-xl p-3 border border-slate-700/60 space-y-2">
              <div className="flex items-center gap-2 text-xs text-emerald-400 font-semibold">
                <PhoneCall className="w-3.5 h-3.5" />
                <span>Kisan Helpline (Toll-Free)</span>
              </div>
              <p className="text-sm font-mono text-white font-bold tracking-wide">
                1800-180-1551
              </p>
              <p className="text-[11px] text-slate-400 leading-tight">
                24/7 Government Agricultural Extension & Weather Support (India)
              </p>
            </div>
          </div>
        </div>

        {/* Bottom bar */}
        <div className="pt-6 flex flex-col sm:flex-row items-center justify-between text-xs text-slate-500 gap-4">
          <p>© {new Date().getFullYear()} AgroAI Assistant. Engineered for agricultural resilience.</p>
          <div className="flex items-center gap-1 text-slate-400">
            <span>Built with precision for farmers</span>
          </div>
        </div>
      </div>
    </footer>
  );
};
